# Generated by Django 3.1.1 on 2020-09-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_name',
            new_name='email',
        ),
    ]
